# Repo Status

In [1]:

from appstore.data.dataset.appdata import AppDataDataset
from appstore.data.dataset.rating import RatingDataset
from appstore.data.dataset.review import ReviewDataset
from appstore.container import AppstoreContainer

container = AppstoreContainer()
container.init_resources()
container.wire(packages=["appstore.data.dataset"])

## Job

In [2]:
repo = container.data.job_repo()
repo.getall()

,id,controller,category_id,category,complete,completed
0,rating-6000,RatingController,6000,Business,True,2023-08-09 07:50:28
1,rating-6002,RatingController,6002,Utilities,True,2023-08-11 14:33:28
2,rating-6005,RatingController,6005,Social_Networking,True,2023-08-09 12:39:38
3,rating-6007,RatingController,6007,Productivity,True,2023-08-09 11:28:53
4,rating-6012,RatingController,6012,Lifestyle,True,2023-07-15 04:20:00
5,rating-6013,RatingController,6013,Health_And_Fitness,True,2023-07-15 04:20:00
6,rating-6015,RatingController,6015,Finance,True,2023-07-15 04:20:00
7,rating-6016,RatingController,6016,Entertainment,True,2023-08-09 09:04:20
8,rating-6017,RatingController,6017,Education,True,2023-08-09 08:31:29
9,rating-6020,RatingController,6020,Medical,True,2023-07-15 04:20:00
10,rating-6023,RatingController,6023,Food_And_Drink,True,2023-07-15 04:20:00
11,rating-6024,RatingController,6024,Shopping,True,2023-08-11 13:52:33
12,review-6000,ReviewController,6000,Business,True,2023-07-15 04:20:00
13,review-6002,ReviewController,6002,Utilities,False,1970-01-01 00:10:00
14,review-6005,ReviewController,6005,Social_Networking,False,1970-01-01 00:10:00
15,review-6007,ReviewController,6007,Productivity,True,2023-07-15 04:20:00
16,review-6012,ReviewController,6012,Lifestyle,False,1970-01-01 00:10:00
17,review-6013,ReviewController,6013,Health_And_Fitness,False,1970-01-01 00:10:00
18,review-6015,ReviewController,6015,Finance,False,1970-01-01 00:10:00
19,review-6016,ReviewController,6016,Entertainment,False,1970-01-01 00:10:00
20,review-6017,ReviewController,6017,Education,False,1970-01-01 00:10:00
21,review-6020,ReviewController,6020,Medical,False,1970-01-01 00:10:00
22,review-6023,ReviewController,6023,Food_And_Drink,False,1970-01-01 00:10:00
23,review-6024,ReviewController,6024,Shopping,False,1970-01-01 00:10:00

## Rating Job Runs

In [3]:
repo = container.data.rating_jobrun_repo()
repo.getall()

,id,jobid,controller,category_id,category,started,ended,elapsed,client_errors,server_errors,data_errors,errors,size,size_ave,apps,apps_per_second,completed,complete,bytes_per_second
0,dfadsldsas5,rating-6000,RatingController,6000,Business,1970-01-01 00:00:10,1970-01-01 00:00:10,236547,22,25,75,122,548953,6.39,85975,2.36,1970-01-01 00:00:10,False,NaN
1,7f0a0f65-93e4-4f31-b24b-625914b934c2,rating-6017,RatingController,6017,Education,2023-08-09 05:00:11,2023-08-09 05:03:59,228,0,0,549,2331,224640,640.00,351,1.54,NaT,False,NaN
2,753751a4-f82b-4da8-92d7-201cb2059db4,rating-6017,RatingController,6017,Education,2023-08-09 05:04:15,2023-08-09 06:06:26,3731,0,0,12017,1624312,7662720,640.00,11973,3.21,2023-08-09 06:06:26,True,NaN
3,50d33605-6d28-42de-a530-e7728059a807,rating-6016,RatingController,6016,Entertainment,2023-08-09 06:06:33,2023-08-09 06:27:39,1266,0,0,3772,210793,3217920,640.00,5028,3.97,NaT,False,NaN
4,0f59b40f-e3e5-45c7-8b6f-e6be28a57b98,rating-6000,RatingController,6000,Business,2023-08-09 06:48:36,2023-08-09 07:50:28,3712,0,0,10375,1206482,6415360,640.00,10024,2.70,2023-08-09 07:50:28,True,NaN
5,8249502a-5ec5-432f-af17-d4ca6e18eac9,rating-6017,RatingController,6017,Education,2023-08-09 07:50:35,2023-08-09 08:31:29,2455,0,0,99,99,640,640.00,1,0.00,2023-08-09 08:31:29,True,NaN
6,31bbbff6-109e-4e09-b8a6-5abc5b268f97,rating-6016,RatingController,6016,Entertainment,2023-08-09 08:31:36,2023-08-09 09:04:20,1964,0,0,5138,276956,2222080,640.00,3472,1.77,2023-08-09 09:04:20,True,NaN
7,b5b06709-d321-461d-bb90-e7fb1f74f958,rating-6024,RatingController,6024,Shopping,2023-08-09 09:04:27,2023-08-09 10:23:37,4750,0,0,16254,2455807,6557440,640.00,10246,2.16,NaT,False,NaN
8,22774a6b-df95-4370-b3c6-7aff6674ec75,rating-6024,RatingController,6024,Shopping,2023-08-09 10:49:06,NaT,0,0,0,0,0,0,0.00,0,0.00,NaT,False,0.00
9,b6888855-9a02-4cc8-9e45-3a05ca888596,rating-6005,RatingController,6005,Social_Networking,2023-08-09 10:56:21,2023-08-09 10:57:38,77,0,0,508,1645,58880,640.00,92,1.19,NaT,False,763.94
10,945b94c0-4cbc-4792-8a68-708b2141828c,rating-6007,RatingController,6007,Productivity,2023-08-09 10:58:50,2023-08-09 10:59:55,65,0,0,305,642,60800,640.00,95,1.45,NaT,False,929.81
11,e53bffa6-37bc-43fb-98b4-9ba8119f9ec3,rating-6007,RatingController,6007,Productivity,2023-08-09 11:06:00,2023-08-09 11:28:53,1373,0,0,3097,195072,4297600,640.00,6715,4.89,2023-08-09 11:28:53,True,"3,130.68"
12,74dd9c6c-744f-40c5-ad16-42dfa21df1b3,rating-6005,RatingController,6005,Social_Networking,2023-08-09 11:29:01,2023-08-09 12:39:38,4237,0,0,13650,1432853,4424320,640.00,6913,1.63,2023-08-09 12:39:38,True,"1,044.28"
13,7253a72f-df48-4c56-a59e-691148ed052e,rating-6024,RatingController,6024,Shopping,2023-08-09 12:39:46,2023-08-09 13:38:27,3521,0,0,1942,22277,165120,640.00,258,0.07,NaT,False,46.89
14,bb6677fb-407d-4528-a748-3269270e91c0,rating-6002,RatingController,6002,Utilities,2023-08-09 21:00:15,2023-08-09 21:06:20,365,0,0,1184,8873,394240,640.00,616,1.69,NaT,False,"1,079.07"
15,4916fd07-4013-46d8-8f24-523b0ae30083,rating-6024,RatingController,6024,Shopping,2023-08-09 21:06:28,2023-08-09 21:08:32,124,0,0,99,99,640,640.00,1,0.01,NaT,False,5.16
16,bc567693-6568-447e-87f6-30939d5e359e,rating-6024,RatingController,6024,Shopping,2023-08-11 12:44:59,2023-08-11 13:52:33,4055,0,0,3222,62116,240640,640.00,376,0.09,2023-08-11 13:52:33,True,59.35
17,127201e7-de62-4c51-a804-a18ded497b1b,rating-6002,RatingController,6002,Utilities,2023-08-11 13:52:41,2023-08-11 14:33:28,2447,0,0,5785,671520,6693760,640.00,10459,4.27,2023-08-11 14:33:28,True,"2,735.55"

## Review Job Runs

In [4]:
repo = container.data.review_jobrun_repo()
repo.getall()

,id,jobid,controller,category_id,category,started,ended,elapsed,client_errors,server_errors,...,errors,size,size_ave,apps,apps_per_second,reviews,reviews_per_second,completed,complete,bytes_per_second
0,dfsoeiwe5w8ew,rating-6000,RatingController,6000,Business,2023-07-15 04:20:20,2023-07-29 04:20:20,236547,22,25,...,122,548953,6.39,85975,2.36,258,5.60,2023-07-15 04:20:20,True,NaN
1,539e1f8d-c1c4-40b6-8111-85028aaaa052,review-6017,ReviewController,6017,Education,2023-08-09 21:03:38,2023-08-09 21:03:51,13,0,0,...,0,10005,"5,002.50",2,0.15,81,6.25,NaT,False,771.50
2,7bc5adca-5134-41fc-bd51-1e69e7477c89,review-6002,ReviewController,6002,Utilities,2023-08-09 21:04:16,2023-08-09 23:18:12,8037,0,0,...,0,4372144,"5,768.00",758,0.09,27159,3.38,NaT,False,544.01
3,6404ab9c-7af5-4c4d-b400-2d629daf9dd6,review-6012,ReviewController,6012,Lifestyle,2023-08-10 03:34:38,2023-08-10 10:58:29,26631,0,0,...,0,211354079,"122,241.00",1729,0.06,1511574,56.76,NaT,False,"7,936.32"
4,baec66a6-db21-483b-84eb-61b99f1b5ccd,review-6002,ReviewController,6002,Utilities,2023-08-10 11:30:02,2023-08-10 19:12:00,27718,0,0,...,0,50445436,"22,360.60",2256,0.08,417409,15.06,NaT,False,"1,819.95"
5,579c399d-31c9-4cf2-8f08-2edf82fa849a,review-6002,ReviewController,6002,Utilities,2023-08-10 19:12:03,2023-08-11 00:13:41,18098,0,0,...,0,7277785,"4,813.35",1512,0.08,41090,2.27,NaT,False,402.12
6,bebe31ca-229c-4fb7-8d06-3fe2b2ae25e4,review-6024,ReviewController,6024,Shopping,2023-08-11 01:13:58,2023-08-11 01:14:04,5,0,0,...,0,1940,"1,940.00",1,0.19,9,1.71,NaT,False,368.80