# Repo Status

In [5]:

from appstore.data.analysis.appdata import AppDataDataset
from appstore.data.analysis.rating import RatingDataset
from appstore.data.analysis.review import ReviewDataset
from appstore.container import AppstoreContainer

container = AppstoreContainer()
container.init_resources()
container.wire(packages=["appstore.data.analysis"])

## Job

In [6]:
repo = container.data.job_repo()
repo.getall()

,id,controller,category_id,category,complete,completed
0,rating-6000,RatingController,6000,Business,True,2023-08-09 07:50:00
1,rating-6002,RatingController,6002,Utilities,False,1970-01-01 00:10:00
2,rating-6005,RatingController,6005,Social_Networking,True,2023-08-09 12:39:00
3,rating-6007,RatingController,6007,Productivity,True,2023-08-09 11:28:00
4,rating-6012,RatingController,6012,Lifestyle,True,2023-07-15 04:20:00
5,rating-6013,RatingController,6013,Health_And_Fitness,True,2023-07-15 04:20:00
6,rating-6015,RatingController,6015,Finance,True,2023-07-15 04:20:00
7,rating-6016,RatingController,6016,Entertainment,True,2023-08-09 09:04:00
8,rating-6017,RatingController,6017,Education,True,2023-08-09 08:31:00
9,rating-6020,RatingController,6020,Medical,True,2023-07-15 04:20:00
10,rating-6023,RatingController,6023,Food_And_Drink,True,2023-07-15 04:20:00
11,rating-6024,RatingController,6024,Shopping,False,1970-01-01 00:10:00
12,review-6000,ReviewController,6000,Business,True,2023-07-15 04:20:00
13,review-6002,ReviewController,6002,Utilities,True,2023-08-09 14:21:26
14,review-6005,ReviewController,6005,Social_Networking,True,1970-01-01 00:10:00
15,review-6007,ReviewController,6007,Productivity,True,2023-07-15 04:20:00
16,review-6012,ReviewController,6012,Lifestyle,True,1970-01-01 00:10:00
17,review-6013,ReviewController,6013,Health_And_Fitness,True,1970-01-01 00:10:00
18,review-6015,ReviewController,6015,Finance,True,1970-01-01 00:10:00
19,review-6016,ReviewController,6016,Entertainment,True,1970-01-01 00:10:00
20,review-6017,ReviewController,6017,Education,True,1970-01-01 00:10:00
21,review-6020,ReviewController,6020,Medical,True,1970-01-01 00:10:00
22,review-6023,ReviewController,6023,Food_And_Drink,True,1970-01-01 00:10:00
23,review-6024,ReviewController,6024,Shopping,True,1970-01-01 00:10:00

## Rating Job Runs

In [7]:
repo = container.data.rating_jobrun_repo()
repo.getall()

,id,jobid,controller,category_id,category,started,ended,elapsed,client_errors,server_errors,data_errors,errors,size,complete,completed,apps,apps_per_second,bytes_per_second,size_ave
0,1e8c850e-3dbf-49ad-8e3d-5f55c3014336,rating-6020,RatingController,6020,Medical,2023-08-09 10:45:18,2023-08-09 10:45:21,3,0,0,0,0,2560,True,2023-08-09 10:45:21,4,1.16,743.18,640.00
1,22bfd8dd-f11d-4f23-b761-e764e3b7e2e2,rating-6017,RatingController,6017,Education,2023-08-09 10:45:22,2023-08-09 10:45:24,2,0,0,4,4,640,True,2023-08-09 10:45:24,1,0.48,304.59,640.00
2,18d7af2e-67b9-4c73-bf79-457f5858dab3,rating-6013,RatingController,6013,Health_And_Fitness,2023-08-09 10:45:24,2023-08-09 10:45:24,0,0,0,0,0,0,True,2023-08-09 10:45:24,0,0.00,0.00,0.00
3,3fc2f986-4ae7-40da-9a51-362245f0d0a8,rating-6015,RatingController,6015,Finance,2023-08-09 10:45:24,2023-08-09 10:45:27,3,0,0,0,0,3200,True,2023-08-09 10:45:27,5,1.80,"1,152.11",640.00
4,254bdc75-798e-40d1-ae71-8903ad281936,rating-6024,RatingController,6024,Shopping,2023-08-09 13:40:47,2023-08-09 13:40:47,0,0,0,0,0,0,True,2023-08-09 13:40:47,0,0.00,0.00,0.00
5,5e838307-21c1-4828-a056-c3217098a571,rating-6002,RatingController,6002,Utilities,2023-08-09 13:40:47,2023-08-09 13:40:47,0,0,0,0,0,0,True,2023-08-09 13:40:47,0,0.00,0.00,0.00

## Review Job Runs

In [8]:
repo = container.data.review_jobrun_repo()
repo.getall()

,id,jobid,controller,category_id,category,started,ended,elapsed,client_errors,server_errors,...,errors,size,size_ave,apps,apps_per_second,reviews,reviews_per_second,completed,complete,bytes_per_second
0,dfsoeiwe5w8ew,rating-6000,RatingController,6000,Business,2023-07-15 04:20:20,2023-07-29 04:20:20,236547,22,25,...,122,548953,6.39,85975,2.36,258,5.60,2023-07-15 04:20:20,True,NaN
1,9ea9a4bb-3602-4d99-abd7-c5b3d719e555,review-6002,ReviewController,6002,Utilities,2023-08-09 14:00:55,NaT,0,0,0,...,0,0,0.00,0,0.00,0,0.00,NaT,False,0.00
2,7e6989fd-e3ad-46b6-a7e0-1a48e592351d,review-6002,ReviewController,6002,Utilities,2023-08-09 14:01:57,NaT,0,0,0,...,0,0,0.00,0,0.00,0,0.00,NaT,False,0.00
3,7e6989fd-e3ad-46b6-a7e0-1a48e592351d,review-6002,ReviewController,6002,Utilities,2023-08-09 14:01:57,NaT,0,0,0,...,0,0,0.00,0,0.00,0,0.00,NaT,False,0.00
4,7e6989fd-e3ad-46b6-a7e0-1a48e592351d,review-6002,ReviewController,6002,Utilities,2023-08-09 14:01:57,NaT,0,0,0,...,0,0,0.00,0,0.00,0,0.00,NaT,False,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,7e6989fd-e3ad-46b6-a7e0-1a48e592351d,review-6002,ReviewController,6002,Utilities,2023-08-09 14:02:21,NaT,0,0,0,...,0,0,0.00,0,0.00,0,0.00,NaT,False,0.00
502,7e6989fd-e3ad-46b6-a7e0-1a48e592351d,review-6002,ReviewController,6002,Utilities,2023-08-09 14:02:21,NaT,0,0,0,...,0,0,0.00,0,0.00,0,0.00,NaT,False,0.00
503,7e6989fd-e3ad-46b6-a7e0-1a48e592351d,review-6002,ReviewController,6002,Utilities,2023-08-09 14:02:21,NaT,0,0,0,...,0,0,0.00,0,0.00,0,0.00,NaT,False,0.00
504,7e6989fd-e3ad-46b6-a7e0-1a48e592351d,review-6002,ReviewController,6002,Utilities,2023-08-09 14:02:21,NaT,0,0,0,...,0,0,0.00,0,0.00,0,0.00,NaT,False,0.00
505,2f378d1b-5612-4ea4-be65-180da51a8678,review-6002,ReviewController,6002,Utilities,2023-08-09 14:21:26,2023-08-09 14:21:26,0,0,0,...,0,0,0.00,0,0.00,0,0.00,2023-08-09 14:21:26,True,0.00