# Repo Status

In [1]:

from appstore.data.dataset.appdata import AppDataDataset
from appstore.data.dataset.rating import RatingDataset
from appstore.data.dataset.review import ReviewDataset
from appstore.infrastructure.file.io import IOService
from appstore.container import AppstoreContainer

container = AppstoreContainer()
container.init_resources()
container.wire(packages=["appstore.data.dataset"])

## Job

In [2]:
df = IOService.read("data/ops/appdata_project.csv")
repo = container.data.project_repo()
repo.replace(data=df)
repo.getall()

Empty DataFrame
Columns: [controller, term, status, page_size, pages, vpages, apps, started, updated, completed, id]
Index: []

## Rating Job Runs

In [3]:
repo = container.data.rating_jobrun_repo()
repo.getall()

ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'appstore_raw.rating_jobrun' doesn't exist")
[SQL: SELECT * FROM rating_jobrun;]
(Background on this error at: https://sqlalche.me/e/20/f405)

## Review Job Runs

In [ ]:
repo = container.data.review_jobrun_repo()
repo.getall()

,id,jobid,controller,category_id,category,started,ended,elapsed,client_errors,server_errors,...,errors,size,size_ave,apps,apps_per_second,reviews,reviews_per_second,completed,complete,bytes_per_second
0,dfsoeiwe5w8ew,rating-6000,RatingController,6000,Business,2023-07-15 04:20:20,2023-07-29 04:20:20,236547,22,25,...,122,548953,6.39,85975,2.36,258,5.60,2023-07-15 04:20:20,True,NaN
1,539e1f8d-c1c4-40b6-8111-85028aaaa052,review-6017,ReviewController,6017,Education,2023-08-09 21:03:38,2023-08-09 21:03:51,13,0,0,...,0,10005,"5,002.50",2,0.15,81,6.25,NaT,False,771.50
2,7bc5adca-5134-41fc-bd51-1e69e7477c89,review-6002,ReviewController,6002,Utilities,2023-08-09 21:04:16,2023-08-09 23:18:12,8037,0,0,...,0,4372144,"5,768.00",758,0.09,27159,3.38,NaT,False,544.01
3,6404ab9c-7af5-4c4d-b400-2d629daf9dd6,review-6012,ReviewController,6012,Lifestyle,2023-08-10 03:34:38,2023-08-10 10:58:29,26631,0,0,...,0,211354079,"122,241.00",1729,0.06,1511574,56.76,NaT,False,"7,936.32"
4,baec66a6-db21-483b-84eb-61b99f1b5ccd,review-6002,ReviewController,6002,Utilities,2023-08-10 11:30:02,2023-08-10 19:12:00,27718,0,0,...,0,50445436,"22,360.60",2256,0.08,417409,15.06,NaT,False,"1,819.95"
5,579c399d-31c9-4cf2-8f08-2edf82fa849a,review-6002,ReviewController,6002,Utilities,2023-08-10 19:12:03,2023-08-11 00:13:41,18098,0,0,...,0,7277785,"4,813.35",1512,0.08,41090,2.27,NaT,False,402.12
6,bebe31ca-229c-4fb7-8d06-3fe2b2ae25e4,review-6024,ReviewController,6024,Shopping,2023-08-11 01:13:58,2023-08-11 01:14:04,5,0,0,...,0,1940,"1,940.00",1,0.19,9,1.71,NaT,False,368.80
7,19169782-41c9-4427-8481-370849f39d30,review-6013,ReviewController,6013,Health_And_Fitness,2023-08-11 15:34:02,2023-08-12 23:49:55,116152,0,0,...,0,584003939,"70,243.40",8314,0.07,3946182,33.98,2023-08-12 23:49:55,True,"5,028.31"
8,26e8bf05-adc3-4c2b-a450-2f7fe6f55af0,review-6016,ReviewController,6016,Entertainment,2023-08-12 23:50:03,2023-08-13 08:17:42,30460,0,0,...,0,267188081,"140,773.00",1898,0.06,2021769,66.38,NaT,False,"8,771.88"
9,78b3d034-61b6-4231-88af-e18d3db71014,review-6012,ReviewController,6012,Lifestyle,2023-08-13 22:28:44,2023-08-14 06:14:51,27967,0,0,...,0,34348530,"16,411.10",2093,0.07,207489,7.42,NaT,False,"1,228.17"
10,671412e0-afe5-49c1-8b0d-cff70100d963,review-6020,ReviewController,6020,Medical,2023-08-14 06:15:35,2023-08-14 07:14:56,3561,0,0,...,0,55395679,"404,348.00",137,0.04,372739,104.67,NaT,False,"15,555.70"
11,30e7dc15-cfe3-46a2-8484-b12c5a833ece,review-6017,ReviewController,6017,Education,2023-08-14 13:02:18,2023-08-15 01:06:53,43474,0,0,...,0,152378594,"49,521.80",3077,0.07,1123214,25.84,NaT,False,"3,505.04"
12,fcccf0c7-c2c1-48f1-8ce0-ea1e85b44ddb,review-6020,ReviewController,6020,Medical,2023-08-18 14:31:08,2023-08-19 00:52:11,37263,0,0,...,0,48571762,"16,720.10",2905,0.08,275054,7.38,2023-08-19 00:52:11,True,"1,303.77"
13,f4767cfd-0776-4fd9-bfaf-694c8894926d,review-6002,ReviewController,6002,Utilities,2023-08-19 00:52:19,2023-08-19 22:55:53,79414,0,0,...,0,330949899,"56,679.20",5839,0.07,2600805,32.75,NaT,False,"4,167.38"
14,c9a40e59-9e68-4672-8253-2cbfbf40e0c7,review-6012,ReviewController,6012,Lifestyle,2023-08-20 00:49:41,2023-08-20 00:53:25,225,0,0,...,0,87375,"3,798.91",23,0.10,477,2.12,NaT,False,388.98
15,404065ad-a817-4e0f-89ae-a9a457e9332e,review-6016,ReviewController,6016,Entertainment,2023-08-20 00:54:08,2023-08-20 00:54:51,44,0,0,...,0,23348,"3,891.33",6,0.14,163,3.74,NaT,False,535.84
16,67e7427f-3235-471c-95c2-f81b95b8ebcf,review-6005,ReviewController,6005,Social_Networking,2023-08-20 00:55:20,2023-08-20 13:54:48,46768,0,0,...,0,336599413,"123,296.00",2730,0.06,2735869,58.50,NaT,False,"7,197.17"